### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by Glench** [Glench/fuzzyset.js#1]
also performance tests

**Comment by panzerdp** [comment]
@Glench 
Thanks for the module. It works just great!

**Comment by dcworldwide** [comment]
I'm guessing tests were not added because over time it's proven to be rock solid?

**Comment by Glench** [comment]
Haha, it's actually out of laziness. But if anyone wanted to make them I'd be happy to accept a pull request.

**Comment by Glench** [comment]
Wanted to leave a note here that basically tests are not needed at this point because it actually *has* proven to be very solid and the library hasn't been changing much. Still would welcome any tests if people wanted to write them!
