### ISSUE TITLE
BSD license identifier

### ISSUE THREAD

**Issue by maruilian11** [Glench/fuzzyset.js#10]
hi, recently we want to add your lib to https://cdnjs.com, I want to confirm the BSD license identifier with you.
thank your very much!

http://spdx.org/licenses/
https://github.com/cdnjs/cdnjs/pull/8900

**Comment by Glench** [comment]
yep! it's BSD as it says in the readme

**Comment by maruilian11** [comment]
hi @Glench,
because BSD has many identifiers, like BSD-2-Clause, BSD-3-Clause and so on, we usually mention it in each lib's package.json in cdnjs, I want to confirm the identifier with you. of course, if you want, I can only mention BSD in license field.
