### ISSUE TITLE
useLevenshtein will always be true?

### ISSUE THREAD

**Issue by cristianocca** [Glench/fuzzyset.js#14]
`fuzzyset.useLevenshtein = useLevenshtein || true;`

That's how the variable is set, correct me if I'm wrong but that won't allow you to pass a false value.

Also I'm trying to understand why the different results with the python version, which in this javascript version doesn't return any match, but the python one does:

```
f = FuzzySet()
f.add(u'Conor Hedley')
print f.get(u'directory manager')
>>> [[(0.23529411764705888, u'Conor Hedley')]
```

**Comment by Glench** [comment]
Hm, are you using the latest version? This is the line I see: https://github.com/Glench/fuzzyset.js/blob/master/lib/fuzzyset.js#L12

**Comment by cristianocca** [comment]
That's odd, yes I'm using version 0.0.1 just as pointed on that file, but that line is different on my local file. Are you sure this is pushed to npm?

**Comment by Glench** [comment]
Definitely not. :) I just pushed version 0.0.2 to npm now, so try updating and everything should work.

**Comment by cristianocca** [comment]
That worked, thanks!
