### ISSUE TITLE
Any way to get more than 1 result?

### ISSUE THREAD

**Issue by cristianocca** [Glench/fuzzyset.js#15]
I know the .get function will return more than 1 result if the match values are the same, and I'm sorry if this is something you are currently working on (since I saw differences in the published and current code just in the lines that builds the results), but the .get function could use an optional parameter to allow more than one result with different scores to be returned.

**Comment by Glench** [comment]
Do you mind giving me an example I can test out to understand further? Just a few entries, an example query, and what you expect to come out would be really helpful!

**Comment by cristianocca** [comment]
Does this capture help? That's the expected result for the query on top. Right now it will only give you the highest match, I know that's what you normally want, but some times is good to see alternative results.

From the version on npm, line 182 is the one that makes sure only the top results are included
```
        for (var i = 0; i < results.length; ++i) {
            if (results[i][0] == results[0][0]) {
                newResults.push([results[i][0], this.exactSet[results[i][1]]]);
            }
        }
```
If the parameter can be passed to the call somewhere, it's as simple as changing that if condition I believe.

![capture](https://cloud.githubusercontent.com/assets/8573267/26745171/b5de3b72-47bf-11e7-8414-df86d5556eb9.PNG)

**Comment by Glench** [comment]
Hm, I think you should try updating through NPM again! v 0.0.3 returns more results and alters the line you're referring to.

**Comment by cristianocca** [comment]
Thanks, I will take a look, can't keep up with the updates :)

**Comment by Glench** [comment]
haha me neither! I just happened to update twice yesterday, which are the only two updates in fuzzyset.js's npm history :P It should be better in the future.
