### ISSUE TITLE
Export/Import already built set?

### ISSUE THREAD

**Issue by j2kun** [Glench/fuzzyset.js#17]
Hi there!

I'm working on a little app that uses a relatively large local databse (200k entries, but small enough to fit on a client machine for the purposes of my project). It takes about 5s to build the index, and I was wondering if it would be possible for me to build the index once, export it to some serialized format, and then bundle it with the app so I don't have to spend so much time building the index when the user loads the page?

If this is possible, how would I do this?

Thanks!

**Comment by Glench** [comment]
Hi @j2kun! I can add this functionality if you like, although it's pretty easy to do it yourself.

To serialize: you could save `yourFuzzyset.exactSet`, `yourFuzzyset.items`, and `yourFuzzyset.matchDict`, maybe by using `JSON.stringify()` on each of those members.

To deserialize: Create an empty FuzzySet object and manually set `yourFuzzyset.matchDict`, `yourFuzzyset.items`, and `yourFuzzyset.exactSet` in your user code.

If you'd like more help doing this, let me know, or I can add the functionality within the library.

**Comment by j2kun** [comment]
Your instructions are great. I will try it, thanks :)

**Comment by j2kun** [comment]
BTW in case you're interested: a demo of the app is (with your fuzzy set powering search) here: http://j2kun.github.io/math-genealogy/index.html

**Comment by Glench** [comment]
neat, thanks!
