### ISSUE TITLE
Return value for get can be an empty array

### ISSUE THREAD

**Issue by lbanders** [Glench/fuzzyset.js#18]
When I do a `get("some value")` I sometimes get an empty array back. 
Is that by intention, that it returns an empty array when there is no match? I know it can also return null in case of no match.

To me it does not seem like consistent behaviour, I just wanted to know if this was intended before making a PR to fix it?

**Comment by Glench** [comment]
You're right, that was unintended behavior. It's been fixed now, thanks!
