### ISSUE TITLE
Being inconsistent

### ISSUE THREAD

**Issue by CheweyZ** [Glench/fuzzyset.js#19]
![image](https://user-images.githubusercontent.com/19643053/29246233-516e068e-8047-11e7-9bd2-9d2e0d9ebdf3.png)
so I had the same match word the whole time and yet when I call it over and over sometimes its works and others don't

whats weird is if I reboot script sometimes all may work and sometimes all won't but even in one test cycle as seen above calling it again it gets a different answer

Note:
Nope is fired when a.get(***) returns null
passed   is when it returns anything

**Comment by Glench** [comment]
Would you mind sharing the strings you fed into the fuzzyset you're using from your screenshot so I can try to replicate the behavior?

**Comment by CheweyZ** [comment]
so here is the wierd part the string is meep but yet ive tried running it on your website and it never fails once

**Comment by CheweyZ** [comment]
what I've started concluding is that if the match is so far out like  no common letter it more often fails to return anything

**Comment by Glench** [comment]
If you could share a script you're making or some code to run, I could try to help you diagnose what's going on.

**Comment by CheweyZ** [comment]
So cant exactly send the exact code due to all the stuff around it although in time have found a"solution" which is just have a `temp[user].answer.get(content)` then if that passes do `temp[user].answer.get(content)[0][0]` and not fatal as it does match everything correctly it just seems odd.
 the way ive used it in context is
`x={}
x['abc']=fuzzySet(['meep'])

function aCallback(content){
if (x['abc].get(content)[0][0]>=0.8){
console.log("hello")
}}`
i was getting fatal from this due to it not returning anything
in the original image sent the left coloum was the value of content in each according time i also had a catch that would be in the event it returned null which is where it would log the result.

**Comment by Glench** [comment]
Sorry, I can't replicate what you're doing so I'm going to close this issue for now. In general when reporting a bug, it's really helpful to give a full description and working demonstration of the bug. Otherwise, the maintainer can't do much. So please make sure you do that before reporting a bug next time!

Best,
Glen
