### ISSUE TITLE
Search results make no sense

### ISSUE THREAD

**Issue by willlma** [Glench/fuzzyset.js#2]
Searching "Con" in demo does not return "Connecticut" (instead, the highest ranked result is "Oregon"). Searching "A" returns "Iowa" rather than the states that start with A. Seaching "K" only returns one of the two K states. 

Surely it should prioritize exact matches and word beginnings over random characters spread throughout the string that happen to be in the correct order.

**Comment by slidenerd** [comment]
I double this, the search is absolutely horrible if it is not going to consider Connecticut over Oregon

**Comment by Glench** [comment]
I agree that it's a weird result, but FuzzySet is only designed to match misspellings, not be a generalized search.

If FuzzySet doesn't match your needs, I would first try play around with the gramSize and useLevenshtein parameters. You can play around with those here: http://glench.github.io/fuzzyset.js/viz/

If Fuzzyset still isn't working for you, it's still very possible to combine it with other logic/libraries that do what you need (for example, prefix matching). I hope you solve your problem!
