### ISSUE TITLE
Not sure about behavior of normalize

### ISSUE THREAD

**Issue by laserpants** [Glench/fuzzyset.js#20]
I am not sure if I understand the normalization step. In the docs, it says that

> fuzzyset will first normalize the string by removing non word characters except for spaces and commas and force everything to be lowercase.

But, the regexp `/[^a-zA-Z0-9\u00C0-\u00FF, ]+/` only replaces the first match. Entering, for instance, `abc^d*E%fwhat` into online debugger gives the following **matchDict**:

```
-a  | (0,1)
ab  | (0,1)
bc  | (0,1)
cd  | (0,1)
d*  | (0,1)
*e  | (0,1)
e%  | (0,1)
%f  | (0,1)
fw  | (0,1)
wh  | (0,1)
ha  | (0,1)
at  | (0,1)
t-  | (0,1)
-ab | (0,1)
abc | (0,1)
bcd | (0,1)
cd* | (0,1)
d*e | (0,1)
*e% | (0,1)
e%f | (0,1)
%fw | (0,1)
fwh | (0,1)
wha | (0,1)
hat | (0,1)
at- | (0,1)
```

Is this the intended result?

Another example:
```
'dsfX1!3 0df,x 00#4.**wat'.replace(/[^a-zA-Z0-9\u00C0-\u00FF, ]+/, '');   
// gives
"dsfX13 0df,x 00#4.**wat"
```
whereas
```
'dsfX1!3 0df,x 00#4.**wat'.replace(/[^a-zA-Z0-9\u00C0-\u00FF, ]/g, '');  
// would produce
"dsfX13 0df,x 004wat"
```

**Comment by Glench** [comment]
Thanks for finding this! I changed the regex to /[^a-zA-Z0-9\u00C0-\u00FF, ]+/g.
