### ISSUE TITLE
Performance with large dictionaries?

### ISSUE THREAD

**Issue by giorgio79** [Glench/fuzzyset.js#22]
Have u tested with Wordnet for example? It has 150 000 entries.

**Comment by Glench** [comment]
Can you please be more specific about what the bug or issue is that you're reporting? What are you doing exactly, what do you expect to happen, and what actually happens?

**Comment by giorgio79** [comment]
Thx for the reply. My question is purely theoretical, eg. how would this lib perform with larger datasets like Wordnet that has 150 thousand entries.

**Comment by Glench** [comment]
Ah ok. I haven't tested it with extremely large dictionaries. It would probably take a while to load all the words into a fuzzyset but once they were there I would expect lookup to be relatively fast considering the library is mostly doing object lookups. The performance could be tweaked by changing the gram size if necessary.
