### ISSUE TITLE
Stable release ?

### ISSUE THREAD

**Issue by bhuvesh40** [Glench/fuzzyset.js#30]
First of all, great work !! I compared like 5-6 libraries for fuzzy search based on my requirements but none came closer to your library. 

The only thing that concerned me was those libraries had like multiple releases. Are you planning to release a stable version any time soon ? I just think it is much better to use and maintain code based on release than on a commit.

**Comment by Glench** [comment]
Releases happen on [npm](https://www.npmjs.com/package/fuzzyset.js?activeTab=versions). It's not really worth the effort in my opinion to create separate release branches on Github. Whatever code is in the master branch should be stable.
