### ISSUE TITLE
Readme not published on npm

### ISSUE THREAD

**Issue by jehy** [Glench/fuzzyset.js#35]
"Unable to find a readme for fuzzyset.js@0.0.7"

**Comment by Glench** [comment]
Seems like a problem on their end. I can't find any documentation about why this is happening except for this: https://github.com/npm/npm/issues/20489 but there are no solutions in that thread.

**Comment by jehy** [comment]
It's the first time I see readme file with .rst extension - may be it's the problem?
In npm/npm#20489  - it seems that republishing package helps...

**Comment by Glench** [comment]
Yeah, I tried that but I can't overwrite the version on npm without bumping
the version and I don't think it's a good idea to bump the version just for
npm's docs.

**Comment by jehy** [comment]
I added a pull request to change readme format because version bump did not solve the problem with readme file: https://github.com/Glench/fuzzyset.js/pull/38
I think that it is fine to bump package with a `patch` version, but you can also merge it to master and publish later with some other changes.

**Comment by Glench** [comment]
merged! thanks for the cleanup!
