### ISSUE TITLE
Correction of input String

### ISSUE THREAD

**Issue by prasadkrn83** [Glench/fuzzyset.js#40]
Is there a way once lemmatization is performed and we get the best match in the defined set of reference string, the input string can be corrected to match the reference text.
For example,
If my reference string is "pick number" and i am trying to match it with "click number three" and then i should be able to correct the word click to pick and get the corrected statement as "pick number three"

**Comment by Glench** [comment]
Hi @prasadkrn83.

If I understand you correctly, I think this library can do what you want, but you have to write a little code to make it match your needs. You could do this:

```javascript
FuzzySet = require('fuzzyset.js')

var fuzzyset = FuzzySet(['click number']);
var input_string = 'pick number three';

// split the string on spaces and test phrases
var test1 = input_string.split(' ').slice(0, 2).join(' ') // 'pick number'
var test2 = input_string.split(' ').slice(1,3).join(' ') // 'number three'

var result = ''
if (fuzzyset.get(test1)) {
    result = input_string.replace(test1, fuzzyset.get(test1)[0][1])
}
console.log(result)
```

Basically you just split the input string by individual phrases (e.g. "pick number" and "number three" if the input is "pick number three", look each of those phrases in the fuzzyset, then if a match is found replace that phrase with the correct one e.g. "click number")
