### ISSUE TITLE
License Clarification

### ISSUE THREAD

**Issue by metalx1000** [Glench/fuzzyset.js#41]
The README.md file says this is licensed under a BSD license, but doesn't state which one.
For me to use this I must follow the license requirements, but there are different BSD licenses.
I believe all BSD licenses require the license to be included with the code.

Could you please clarify which BSD license is used here?
And technically the license should be included in this project.

**Comment by Glench** [comment]
@axiak can you clarify this or can I release under another license?

**Comment by Glench** [comment]
Alright, I updated the license to be something else entirely. Thanks for opening the issue and sorry for the delay.
