### ISSUE TITLE
in mongo

### ISSUE THREAD

**Issue by pvcon13** [Glench/fuzzyset.js#42]
This is not an issue, just a question where else to look. Any idea how this could be easily used inside a mongodb find (instead of their regex solutions)?

**Comment by Glench** [comment]
Unfortunately I don’t know anything about mongo. Maybe you could take a look at the interactive documentation and see if there’s a way you could recreate the functionality in mongo.

**Comment by pvcon13** [comment]
I really like what you module does. Thanks for it.
