### ISSUE TITLE
fuzzyset Minimum score does not work [python]

### ISSUE THREAD

**Issue by gosforth** [Glench/fuzzyset.js#44]
fuzzy_data = FuzzySet()
 fuzzy_data.add('something')
 result = fuzzy_data.get('someing', 0.21)

Whatever I type there in third line as minimum score it has no influence on result. Am I doing something wrong?

**Comment by Glench** [comment]
you need 3 arguments and the third is the match score:

`FuzzySet.get(value, [default], [minScore=.33])`

**Comment by gosforth** [comment]
What is "default"? I tried with 3 arguments but I got error that only 2 are accepted. Could you please provide example? Python

**Comment by Glench** [comment]
This is the JavaScript version of the library, which made some significant changes based on user feedback. For the python version documentation, go here: https://github.com/axiak/fuzzyset

**Comment by gosforth** [comment]
OK, thanks. So it does not support it. What can be "default" argument in JS version?

**Comment by Glench** [comment]
Default can be any value you want. It’s the value you want returned if no entries are found. It’s set to be null if not provided.

**Comment by gosforth** [comment]
Thank you very much - you motivated me to use JS edition :-)
