### ISSUE TITLE
module export for TypeScript

### ISSUE THREAD

**Issue by danbraik** [Glench/fuzzyset.js#46]
Hello,
first thank you for your wonderful library !

I am writing an app with TypeScript and importing it like :
`import { FuzzySet } from 'fuzzyset';`

but when instanciating,
`this._fuzzySet = FuzzySet();`

 I got this error : 
`ERROR TypeError: Object(...) is not a function`.

If I am correct, to allow your library to be TypeScript compatible, you can just update the final line to
`module.exports.FuzzySet = FuzzySet;`
(it may change the way to use it in vanilla JS)

Best regards !

**Comment by carloscolombo** [comment]
The following worked for me:
`import * as FuzzySet from 'fuzzyset.js';`

**Comment by Glench** [comment]
hey, this should be fixed in 513d39141305243eabe06e399c8a10fe3f1a7b46! Anybody want to test?
