### ISSUE TITLE
Better structure for releases & versioning

### ISSUE THREAD

**Issue by BlitZz96** [Glench/fuzzyset.js#48]
First of all, I must thank you for this nice repo!
I would however like to advice you to keep a better structure on your versioning and hopefully also use releases. 

## Why should you do this?
When people like me (and the other 1.1k users starred it) sees there is an update in this repo's version - It is really hard to figure out what has been done and what we need to do to keep our systems working as intended. I am not sure if you are aware of the term "Semantic Versioning", but in general, it is a common assumption that developers use to understand a package's changes. 

In example, you just changed this repo's version from [0.0.91 to 1.0.0](https://github.com/Glench/fuzzyset.js/commit/e1e20ea374c6a09a17c26c01e109dfffd9b29fe2.
If you used semantic versioning, this would mean that a change you made to the core API would cause the usage of the repo version >1.0.0  to be incompatible to this new change; We who used your package would have to re-write some code if we were affected by that specific change.

As you understand, this is a bit confusing for a lot of developers, like myself.

Therefore, I would suggest you to look in to semantic versioning and hopefully also use Github releases - Then you type specific info regarding that particular release.

Thanks! 😄

**Comment by Glench** [comment]
Hey thanks for writing! The reason I changed the version is because I changed the license of the library which significantly changes where and how it can be used. The API stayed the same. Going forward I will continue to use semantic versioning to keep with how the library’s functions and structure changes.

**Comment by BlitZz96** [comment]
Thank you for the quick answer. Now I see. I had not gone though all of your commits in order to see this change. This is a perfect example on how releases would help out. This way, people can compare the "readmes" for the different version from theirs. In this case, you updated your lisence to non-commertial. I would never have picked up this change if you didn't just tell me now 😅 

Have a good day, and good luck with your therapy career! 🎉  😃
