### ISSUE TITLE
Question: Why are you exporting both to module and window in CommonJS?

### ISSUE THREAD

**Issue by nordfjord** [Glench/fuzzyset.js#5]
your last lines look like so:

``` js
if (typeof module !== 'undefined' && module.exports) {
    module.exports = FuzzySet;
    root.FuzzySet = FuzzySet;
} else {
    root.FuzzySet = FuzzySet;
}
```

For me the point of using CommonJS is at least to some extent isolation of components. If I wanted the module to be exported globally I could do so in my own code like so:

``` js
window.FuzzySet = require('fuzzyset.js');
```

I'm just wondering if there's any particular reason you decided to double export.

**Comment by Glench** [comment]
I have no idea how this stuff works, but nobody is complaining so 👍
