### ISSUE TITLE
Do you have idea how can I use it with large database (120.000 rows)? 

### ISSUE THREAD

**Issue by gosforth** [Glench/fuzzyset.js#50]
I would like to find similar product name in database with 120.000 rows.
Exporting all to javascript object will be not possible - sql will not support so many characters.
Regards

**Comment by Glench** [comment]
I'm afraid I don't know of any off-hand and would have to search for solutions.

However, it might be possible to build your own following the principles of this library which you can learn about in-depth here: https://glench.github.io/fuzzyset.js/ui/index.html
