### ISSUE TITLE
[Question] Support of multiple languages

### ISSUE THREAD

**Issue by bacloud14** [Glench/fuzzyset.js#53]
I went through the demo [here](http://glench.github.io/fuzzyset.js/) and I don't know why but Calculating the dot product of two vectors when values are Arabic, score is 0 for this example:
```
لمادا

لماذا
```

Thanks a lot @Glench !!!!

**Comment by Glench** [comment]
Thanks for testing this out! You can actually use the rest of that demo to see where things go awry: http://glench.github.io/fuzzyset.js/ui/

Looks like the gramCounter function isn't working. I'll check if this is a bug in the actual library later.

**Comment by bacloud14** [comment]
Thanks @Glench Indeed `gramCounter`  is not working.

**Comment by bacloud14** [comment]
All I can help with, is [this](https://stackoverflow.com/questions/16664267/text-matching-not-working-for-arabic-issue-may-be-due-to-regex-for-arabic) which seems a popular issue, just in case you are using such Regex under the carpet.

**Comment by bacloud14** [comment]
It is because of this `var _nonWordRe = /[^a-zA-Z0-9\u00C0-\u00FF, ]+/g;` which is used by 
https://github.com/Glench/fuzzyset.js/blob/916ce6297438cd9e4b1de184efe05a5b29f3d117/dist/fuzzyset.js#L56

**Comment by bacloud14** [comment]
I'm not sure though

```
var _nonWordRe = /[^a-zA-Z0-9\u00C0-\u00FF, ]+ | ([\u0600-\u06ff]+)([^\u0600-\u06ff]+)?/g;
'-' + "hello".toLowerCase().replace(_nonWordRe, '') + '-';
'-hello-'
'-' + "مرحبا".toLowerCase().replace(_nonWordRe, '') + '-';
'-مرحبا-'
```

```
var _nonWordRe = /[^a-zA-Z0-9\u00C0-\u00FF, ]+/g;
'-' + "مرحبا".toLowerCase().replace(_nonWordRe, '') + '-';
'--'
'-' + "hello".toLowerCase().replace(_nonWordRe, '') + '-';
'-hello-'
```

I could use something similar to comprehend english and arabic, but I'm 90% sure I'm messing things.

**Comment by bacloud14** [comment]
```
fuzzyset = FuzzySet(['Mississippi', 'Missouri', 'California'], false, 3,3)
const similarity = fuzzyset.get('mossisippi')
console.log(similarity)
```

This is what I exactly needed by the way, 🥇

**Comment by Glench** [comment]
Okay, I added arabic support. I don't think other alphabets are supported at the moment but if someone needs this then please write a comment here.

**Comment by ghost** [comment]
Thanks a lot @Glench for the addition 🥳
