### ISSUE TITLE
Incorrect link in sidebar

### ISSUE THREAD

**Issue by Tc-001** [Glench/fuzzyset.js#54]
Link in the repository's sidebar leads to `https://glench.github.com/fuzzyset.js/` (`github.com`) , which is a 404.

It should lead to `https://glench.github.io/fuzzyset.js/` (`github.io`), where github hosts their pages.

![image](https://user-images.githubusercontent.com/55956895/145730653-46360ac1-3cb5-4759-8b26-e7b513b069ec.png)

**Comment by Glench** [comment]
thanks, fixed!
