### ISSUE TITLE
Add support for objects matching.

### ISSUE THREAD

**Issue by slawo** [Glench/fuzzyset.js#7]
There should be a way search within an array of objects.

**Comment by Glench** [comment]
I'm afraid that's outside the scope of this library. One can easily do a transform to get the object data into this library.

**Comment by mousavian** [comment]
Having this could be very useful.
So user is able to add a list of objects, search & match on specific key, and return respective object if found any match.

I can implement this and send a PR in case you agree. :)

**Comment by SuddenGunter** [comment]
I know this is necroposting, but still: @slawo @mousavian @Glench any chances anybody of you implemented this?

**Comment by MINORITYmaN** [comment]
> I know this is necroposting, but still: @slawo @mousavian @Glench any chances anybody of you implemented this?

have you tried https://github.com/seiyria/fuzzyset-obj ?

**Comment by MINORITYmaN** [comment]
> I know this is necroposting, but still: @slawo @mousavian @Glench any chances anybody of you implemented this?

have you tried https://github.com/seiyria/fuzzyset-obj ?
